### PR TITLE
Update COSQuickRef.md

### PR DESCRIPTION
**Pull request by isc-solon**
Since the beginning of this repo, it's bothered me that we can't use italics for placeholders in code in markdown. So I added the "Name" convention **note** at the top and updated many places throughout. While I was editing I made some other corrections and I added a few things that I've added to my course's version of this material. The reason that this all happened today is that the recent InterSystems Learning Services newsletter has a link to this material now, in a new feature they're calling "Quick Wins" so I wanted to improve it.

### CODE REVIEW

**Comment by eduard93** [comment]
Markdown supports *italicized text*.

Source:
```
Markdown supports *italicized text*.
```

**Comment by tsafin** [comment]
@eduard93 but not if you want to put italics *inside* of ``code`` block
`Do ##class(packageName.className).*methodName*(arguments)`

**Comment by isc-solon** [comment]
Yes, **that's** the reason we didn't do it in the first place.

**Comment by isc-solon** [comment]
I believe that I used to have full privs to commit stuff in this repo, but I don't anymore (which is fine). So would one of you commit this please?

**Comment by evshvarov** [comment]
I am OK. @eduard?

вт, 4 авг. 2020 г. в 00:08, Joel Solon <notifications@github.com>:

**Comment by eduard93** [comment]
Yes, merged.

**Pull request merged**
